{
 "title": "Mattermost Notification Health",
 "description": "A dashboard displaying notification health metrics, and distributions around notifications that were not sent, both deliberate and indeliberate. \n\nThe dashboard is split in half by Websocket events (POSTED events from the server to web clients) and Push events (events sent to the push proxy to be received by mobile clients).",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "platform", "label": "Platform", "query": "ios, android" }
  ]
 },
 "panels": [
  {
   "title": "Websocket Notification Health",
   "type": "stat",
   "description": "A running total of the number of notifiable websocket events acknowledged by the server vs. the number sent. A notifiable event is any POSTED event that may result in a notification on the web client.\n\nThe smaller number indicates the percent change over the selected date range, while the larger number is the absolute total.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$Acked/$Sent", "type": "math" }
   ]
  },
  {
   "title": "Total Push Notification Health",
   "type": "stat",
   "description": "A running total of the number of push notifications acknowledged by the server vs. the number sent.\n\nThe smaller number indicates the percent change over the selected date range, while the larger number is the absolute total.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$Acked/$Sent", "type": "math" }
   ]
  },
  {
   "title": "Push Proxy Delivery Rate",
   "type": "stat",
   "description": "Shows the percentage of notifications sent to the push proxy that were properly handled by it.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($Success/($Success+$Fail))", "type": "math" }
   ]
  },
  {
   "title": "Websocket Notification Stats",
   "type": "timeseries",
   "description": "A graph that shows the change in the notification health over time, with respect to websocket notifiable events. As the gap between sent vs. acked widens, the number of not acknowledged events will go up (calculated as the difference of the above values)",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(mattermost_notifications_total{type=\"websocket\"}) OR vector(0)",
     "legendFormat": "Notifiable Events Sent"
    },
    {
     "expr": "sum(mattermost_notifications_total_ack{type=\"websocket\"}) OR vector(0)",
     "legendFormat": "Notifiable Events Acknowledged"
    },
    { "expression": "$Sent-$Acked", "type": "math" }
   ]
  },
  {
   "title": "Websocket Sent vs. Not Sent",
   "type": "stat",
   "description": "Displays the total number of acknowledged notifiable events over the given range. If \"Bad range\" is shown, that means the counter was reset and the value cannot be accurately determined. It is advised to pick a date range in which the counter has not been reset (resets will happen after the server has been restarted).\n\nThe Sent number indicates the number of events that resulted in a notification to the end user, and not sent is the number of events where the system decided not to send the notification.\n\nIf shown, Unknown indicates the number of events where we could not determine the result of the event. This usually indicates an out-of-date Desktop App.",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(mattermost_notifications_unsupported{type=\"websocket\"}) OR vector(0)",
     "legendFormat": "Total Notifications Unknown"
    },
    {
     "expr": "sum(mattermost_notifications_not_sent{type=\"websocket\"}) OR vector(0)",
     "legendFormat": "Total Notifications Not Sent"
    },
    {
     "expr": "sum(mattermost_notifications_success{type=\"websocket\"}) OR vector(0)",
     "legendFormat": "Total Notifications Sent"
    }
   ]
  },
  {
   "title": "Push Notification Stats",
   "type": "timeseries",
   "description": "A graph that shows the change in the notification health over time, with respect to push notifications. As the gap between sent vs. acked widens, the number of not acknowledged events will go up (calculated as the difference of the above values)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(mattermost_notifications_total{type=\"push\", platform!=\"$platform\"}) OR vector(0)",
     "legendFormat": "Push Notifications Sent"
    },
    {
     "expr": "sum(mattermost_notifications_total_ack{type=\"push\", platform!=\"$platform\"}) OR vector(0)",
     "legendFormat": "Push Notifications Acknowledged"
    },
    { "expression": "$Sent-$Acked", "type": "math" }
   ]
  },
  {
   "title": "Websocket Notification Errors by Reason",
   "type": "bargauge",
   "description": "A breakdown of any errors affecting the sending of websocket notifications by reason. These may occur at the server, or the client and do not directly correlate with the notifiable event success.\n\nErrors that occur here should show up in the server notification logs, and can be investigated there.",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum by(reason) (mattermost_notifications_error{type=\"websocket\"})",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Websocket Notifications Not Sent Distribution",
   "type": "piechart",
   "description": "Displays the distribution of reasons that users may not be sent notifications via the websocket when handled correctly by the system. This is helpful to diagnose where user settings or system design may contribute to missing notifications.",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum by(reason) (mattermost_notifications_not_sent{type=\"websocket\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Push Notification Errors by Reason",
   "type": "bargauge",
   "description": "A breakdown of any errors affecting the sending of push notifications by reason. These may occur at the server, or the client and do not directly correlate with the notifiable event success.\n",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum by(reason) (mattermost_notifications_error{type=\"push\", platform=~\"$platform|no_platform\"})",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Push Notifications Not Sent Distribution",
   "type": "piechart",
   "description": "Displays the distribution of reasons that users may not be sent push notifications when handled correctly by the system. This is helpful to diagnose where user settings or system design may contribute to missing notifications.",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum by(reason) (mattermost_notifications_not_sent{type=\"push\"})",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Email Notifications",
   "type": "stat",
   "description": "Shows a breakdown of reasons that email notifications may fail to be sent from the server.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum by(reason) (mattermost_notifications_not_sent{type=\"email\"})",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "sum by(reason) (mattermost_notifications_error{type=\"email\"})",
     "legendFormat": "{{reason}}"
    }
   ]
  }
 ]
}