{
 "title": "Mattermost Performance Monitoring",
 "tags": [
  "mattermost",
  "mattermost-perf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "server", "label": "server", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Number of Messages per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_post_total{instance=~\"$server\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(mattermost_post_total{instance=~\"$server\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of API Errors per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_http_errors_total{instance=~\"$server\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(mattermost_http_errors_total{instance=~\"$server\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Connected Devices (WebSocket Connections)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "mattermost_http_websockets_total{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(mattermost_http_websockets_total{instance=~\"$server\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Connections to Master Database",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "mattermost_db_master_connections_total{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(mattermost_db_master_connections_total{instance=~\"$server\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Connections to Read Replica Databases",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "mattermost_db_read_replica_connections_total{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(mattermost_db_read_replica_connections_total{instance=~\"$server\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Connections to Search Replica Databases",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "mattermost_db_search_replica_connections_total{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(mattermost_db_search_replica_connections_total{instance=~\"$server\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Messages Per Second by Type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mattermost_post_webhooks_total[1m]))",
     "legendFormat": "Webhooks"
    },
    {
     "expr": "sum(irate(mattermost_post_total[1m])*10)-sum(irate(mattermost_post_webhooks_total[1m]))",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Number of Broadcasts per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_post_broadcasts_total{instance=~\"$server\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(mattermost_post_broadcasts_total{instance=~\"$server\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU Utilization Rate (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "Utilization Rate (%)" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_process_cpu_seconds_total{instance=~\"$server\"}[1m])* 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mean API Request Time (in milliseconds)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds (ms)" }
   ],
   "targets": [
    {
     "expr": "1000.0 * rate(mattermost_http_request_duration_seconds_sum{instance=~\"$server\"}[1m]) /   rate(mattermost_http_request_duration_seconds_count{instance=~\"$server\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mean Cluster Request Time (in milliseconds)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds (ms)" }
   ],
   "targets": [
    {
     "expr": "1000.0 * rate(mattermost_cluster_cluster_request_duration_seconds_sum{instance=~\"$server\"}[1m]) /  rate(mattermost_cluster_cluster_request_duration_seconds_count{instance=~\"$server\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Go Routines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(go_goroutines{instance=~\"$server\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Usage (in MB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=~\"$server\"}/1024/1024",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(go_memstats_alloc_bytes{instance=~\"$server\"})/1024/1024",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}