{
 "title": "Web App Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Interactivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Channel Switch",
   "type": "timeseries",
   "description": "The time between when a user clicks on a channel in the LHS and when posts in that channel are shown to them, measured as a percentile of all requests in a given 30 minute period",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum by(le) (increase(mattermost_webapp_channel_switch_bucket{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$decay])))",
     "legendFormat": "[[percentile]]th Percentile"
    }
   ]
  },
  {
   "title": "Channel Switch (Overall)",
   "type": "stat",
   "description": "The [[percentile]]th percentile of all Channel Switch measurements over the selected time period and the number of measurements taken during that time.\n\nTarget values for P75:\n- Good: 250ms\n- Needs Improvement: 500ms",
   "gridPos": { "h": 16, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum by(le) (increase(mattermost_webapp_channel_switch_bucket{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$__range])))",
     "legendFormat": "[[percentile]]th Percentile"
    },
    {
     "expr": "sum(increase(mattermost_webapp_channel_switch_count{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$__range]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Team Switch",
   "type": "timeseries",
   "description": "The time between when a user clicks on a team in the LHS and when posts in a channel on that team are shown to them",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum by(le) (increase(mattermost_webapp_team_switch_bucket{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$decay])))",
     "legendFormat": "[[percentile]]th Percentile"
    }
   ]
  },
  {
   "title": "Team Switch (Overall)",
   "type": "stat",
   "description": "The [[percentile]]th percentile of all Team Switch measurements over the selected time period and the number of measurements taken during that time.\n\nTarget values for P75:\n- Good: 750ms\n- Needs Improvement: 1.25s",
   "gridPos": { "h": 16, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum by(le) (increase(mattermost_webapp_team_switch_bucket{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$__range])))",
     "legendFormat": "[[percentile]]th Percentile"
    },
    {
     "expr": "sum(increase(mattermost_webapp_team_switch_count{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$__range]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "# of Channel Switches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_webapp_channel_switch_count{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$decay]))",
     "legendFormat": "# of Reports"
    }
   ]
  },
  {
   "title": "# of Team Switches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_webapp_team_switch_count{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$decay]))",
     "legendFormat": "# of Reports"
    }
   ]
  },
  {
   "title": "RHS Load",
   "type": "timeseries",
   "description": "The time between when a user clicks to open the RHS and when the VirtualizedThreadViewer component is mounted, measured as a percentile of all requests in a given 30 minute period",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum by(le) (increase(mattermost_webapp_rhs_load_bucket{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$decay])))",
     "legendFormat": "[[percentile]]th Percentile"
    }
   ]
  },
  {
   "title": "RHS Load (Overall)",
   "type": "stat",
   "description": "The [[percentile]]th percentile of all RHS Load measurements over the selected time period and the number of measurements taken during that time.\n\nTarget values for P75:\n- Good: 350ms\n- Needs Improvement: 600ms",
   "gridPos": { "h": 16, "w": 2, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum by(le) (increase(mattermost_webapp_rhs_load_bucket{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$__range])))",
     "legendFormat": "[[percentile]]th Percentile"
    },
    {
     "expr": "sum(increase(mattermost_webapp_rhs_load_count{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$__range]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Threads List Load",
   "type": "timeseries",
   "description": "The time between when a user clicks on Threads in the LHS and when a list of threads is rendered, measured as a percentile of all requests in a given 30 minute period",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum by(le) (increase(mattermost_webapp_global_threads_load_bucket{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$decay])))",
     "legendFormat": "[[percentile]]th Percentile"
    }
   ]
  },
  {
   "title": "Threads List Load (Overall)",
   "type": "stat",
   "description": "The [[percentile]]th percentile of all Threads List Load measurements over the selected time period and the number of measurements taken during that time.\n\nTarget values for P75:\n- Good: 500ms\n- Needs Improvement: 800ms",
   "gridPos": { "h": 16, "w": 2, "x": 22, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum by(le) (increase(mattermost_webapp_global_threads_load_bucket{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$__range])))",
     "legendFormat": "[[percentile]]th Percentile"
    },
    {
     "expr": "sum(increase(mattermost_webapp_global_threads_load_count{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$__range]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "# of RHS Loads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_webapp_rhs_load_count{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$decay]))",
     "legendFormat": "# of Reports"
    }
   ]
  },
  {
   "title": "# of Threads List Loads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_webapp_global_threads_load_count{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$decay]))",
     "legendFormat": "# of Reports"
    }
   ]
  },
  {
   "title": "Interaction to Next Paint (INP)",
   "type": "timeseries",
   "description": "Tracks the duration of the longest click or keyboard interaction during an application's lifecycle (Desktop/Chrome/Edge only)",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum by(le) (increase(mattermost_webapp_interaction_to_next_paint_bucket{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$decay])))",
     "legendFormat": "[[percentile]]th Percentile"
    }
   ]
  },
  {
   "title": "INP (Overall)",
   "type": "stat",
   "description": "The [[percentile]]th percentile of all Interaction to Next Paint measurements over the selected time period and the number of measurements taken during that time.\n\nTarget values for P75:\n- Good: 200ms\n- Needs Improvement: 500ms",
   "gridPos": { "h": 16, "w": 2, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum by(le) (increase(mattermost_webapp_interaction_to_next_paint_bucket{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$__range])))",
     "legendFormat": "[[percentile]]th Percentile"
    },
    {
     "expr": "sum(increase(mattermost_webapp_interaction_to_next_paint_count{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$__range]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Long Tasks",
   "type": "timeseries",
   "description": "The number of times that the main UI thread of a browser was blocked for more than 50ms (Desktop/Chrome/Edge only)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(mattermost_webapp_long_tasks{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[10m]))",
     "legendFormat": "# of Long Tasks per second"
    }
   ]
  },
  {
   "title": "# of INPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_webapp_interaction_to_next_paint_count{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$decay]))",
     "legendFormat": "# of Reports"
    }
   ]
  },
  { "title": "Initial Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Time to First Byte (TTFB)",
   "type": "timeseries",
   "description": "Tracks the time from when a browser first requests data from the server until when the browser starts to receive a response",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum by(le) (increase(mattermost_webapp_time_to_first_byte_bucket{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$decay])))",
     "legendFormat": "[[percentile]]th Percentile"
    }
   ]
  },
  {
   "title": "TTFB (Overall)",
   "type": "stat",
   "description": "The [[percentile]]th percentile of all Time To First Byte measurements over the selected time period and the number of measurements taken during that time.\n\nTarget values for P75:\n- Good: 800ms\n- Needs Improvement: 1.8s",
   "gridPos": { "h": 16, "w": 2, "x": 10, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum by(le) (increase(mattermost_webapp_time_to_first_byte_bucket{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$__range])))",
     "legendFormat": "[[percentile]]th Percentile"
    },
    {
     "expr": "sum(increase(mattermost_webapp_time_to_first_byte_count{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$__range]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Load Event End (Formerly Page Load)",
   "type": "timeseries",
   "description": "The time between when the browser starts to load the web app and when the `window.load` event completes which is before much of the web app is loaded.",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum by(le) (increase(mattermost_webapp_page_load_bucket{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$decay])))",
     "legendFormat": "[[percentile]]th Percentile"
    }
   ]
  },
  {
   "title": "Load Event End (Overall)",
   "type": "stat",
   "description": "The [[percentile]]th percentile of all Load Event End measurements over the selected time period and the number of measurements taken during that time.\n\nTarget values for P75:\n- Good: 2.25s\n- Needs Improvement: 4.5s",
   "gridPos": { "h": 16, "w": 2, "x": 22, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum by(le) (increase(mattermost_webapp_page_load_bucket{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$__range])))",
     "legendFormat": "[[percentile]]th Percentile"
    },
    {
     "expr": "sum(increase(mattermost_webapp_page_load_count{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$__range]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "# of TTFBs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_webapp_time_to_first_byte_count{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$decay]))",
     "legendFormat": "# of Reports"
    }
   ]
  },
  {
   "title": "# of Load Event Ends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_webapp_page_load_count{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$decay]))",
     "legendFormat": "# of Reports"
    }
   ]
  },
  {
   "title": "First Contentful Paint (FCP)/Largest Contentful Paint (LCP)",
   "type": "timeseries",
   "description": "FCP tracks the amount of time taken from when a page starts to load to when the first content on that page is visible. LCP tracks the amount of time taken until a large piece of content is visible. (Only on Desktop/Firefox/Chrome/Edge)",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum by(le) (increase(mattermost_webapp_first_contentful_paint_bucket{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$decay])))",
     "legendFormat": "FCP [[percentile]]th Percentile"
    },
    {
     "expr": "histogram_quantile($percentile / 100, sum by(le) (increase(mattermost_webapp_largest_contentful_paint_bucket{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$decay])))",
     "legendFormat": "LCP [[percentile]]th Percentile"
    }
   ]
  },
  {
   "title": "FCP (Overall)",
   "type": "stat",
   "description": "The [[percentile]]th percentile of all First Contentful Paint measurements over the selected time period and the number of measurements taken during that time.\n\nTarget values for P75:\n- Good: 1.8s\n- Needs Improvement: 3s",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum by(le) (increase(mattermost_webapp_first_contentful_paint_bucket{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$__range])))",
     "legendFormat": "[[percentile]]th Percentile"
    },
    {
     "expr": "sum(increase(mattermost_webapp_first_contentful_paint_count{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$__range]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift (CLS)",
   "type": "timeseries",
   "description": "A measurement of how much page layout shifts unexpectedly (Desktop/Chrome/Edge only)",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum by(le) (increase(mattermost_webapp_cumulative_layout_shift_bucket{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$decay])))",
     "legendFormat": "[[percentile]]th Percentile"
    }
   ]
  },
  {
   "title": "CLS (Overall)",
   "type": "stat",
   "description": "The [[percentile]]th percentile of all Cumulative Layout Shift measurements over the selected time period and the number of measurements taken during that time.\n\nTarget values for P75:\n- Good: 0.1\n- Needs Improvement: 0.25",
   "gridPos": { "h": 16, "w": 2, "x": 22, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum by(le) (increase(mattermost_webapp_cumulative_layout_shift_bucket{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$__range])))",
     "legendFormat": "[[percentile]]th Percentile"
    },
    {
     "expr": "sum(increase(mattermost_webapp_cumulative_layout_shift_count{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$__range]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "# of FCPs/LCPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_webapp_first_contentful_paint_count{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[10m]))",
     "legendFormat": "# of FCP Reports"
    },
    {
     "expr": "sum(increase(mattermost_webapp_largest_contentful_paint_count{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[10m]))",
     "legendFormat": "# of LCP Reports"
    }
   ]
  },
  {
   "title": "LCP (Overall)",
   "type": "stat",
   "description": "The [[percentile]]th percentile of all Largest Contentful Paint measurements over the selected time period and the number of measurements taken during that time.\n\nTarget values for P75:\n- Good: 2.5s\n- Needs Improvement: 4s",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum by(le) (increase(mattermost_webapp_largest_contentful_paint_bucket{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$__range])))",
     "legendFormat": "[[percentile]]th Percentile"
    },
    {
     "expr": "sum(increase(mattermost_webapp_largest_contentful_paint_count{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$__range]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "# of CLSs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_webapp_interaction_to_next_paint_count{namespace=~\"$namespace\",agent=~\"$agent\",platform=~\"$platform\"}[$decay]))",
     "legendFormat": "# of Reports"
    }
   ]
  },
  { "title": "Other Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } }
 ]
}